# Generated by Django 2.2 on 2020-08-22 12:48

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("api", "0002_auto_20200822_1247"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="authuser", managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.AlterField(
            model_name="authuser", name="date_joined", field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(model_name="authuser", name="is_active", field=models.BooleanField(default=False),),
        migrations.AlterField(model_name="authuser", name="is_staff", field=models.BooleanField(default=False),),
        migrations.AlterField(model_name="authuser", name="is_superuser", field=models.BooleanField(default=False),),
    ]
