# Generated by Django 2.2 on 2020-08-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("api", "0003_auto_20200822_1248"),
    ]

    operations = [
        migrations.AddField(
            model_name="authuser",
            name="profile_pic",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
    ]
